# Site settings
title: Yilun Sheng
description: 'Personal academic portfolio of Yilun Sheng'
url: 'https://ayluuur.github.io'
baseurl: ''
profilepic: '/assets/%E8%AF%81%E4%BB%B6%E7%85%A7.jpg'
bkimage: '/images/bk1.jpg'

author:
  name: 'Yilun Sheng'
  email: yilun205@163.com
  github_username: Ayluuur

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  input: GFM
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
